# Project Information
site_name: USTC CS Board
site_description: USTC Computer Science (Grade 2016) Course Board
site_author: Jiyan He
site_url: https://cs.volltin.com/

# Repository
repo_name: 'volltin/ustc-cs-borad'
repo_url: 'https://github.com/volltin/ustc-cs-borad'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2018 USTC CS Board Team'

# Contents
pages:
  - 首页:
    - 简介: index.md
    - Contributing: contributing.md
  - 计算机网络（张）:
    - 作业和实验: net/zhang/hw.md
    - 课程信息: net/zhang/info.md
    - 联系方式: net/zhang/contact.md
  - 计算机网络（田）:
    - 作业和实验: net/tian/hw.md
    - 课程信息: net/tian/info.md
    - 联系方式: net/tian/contact.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'

extra_javascript:
  # - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

# extra_css:
#   - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
